services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LinkORB\Bundle\SpicedbBundle\:
    resource: '../src/*'

  LinkORB\Authzed\ConnectorInterface: '@LinkORB\Authzed\SpiceDB'
